device: 'cuda'

name: 'haystack-surt-randomized-projection-depth_exp_250317-171056'
load_iter: 47500
phase: 'test'
checkpoints_dir: '/scratch/park/checkpoints/models/DeepClarity'
results_dir: '/scratch/park/results/DeepClarity'
skip_real: True
verbose: False
save_volume: True 
eval: True 

inference_parameters:
  batch_size: 1
  gpu_ids: [0] # gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU
  preprocess: addColorChannel # preprocessing for input images: [randomcrop | randomrotate | randomflip | normalize | none]
  dicing_parameters:
  patch_size: [48, 128, 128] # x, y, z
  patch_overlap: 20
  data_type: 'uint16'

data_parameters:
  data_source: '/scratch/park/data/simulation_data/haystack/6000-lines-blurred-by-gaublur-std-4/bornandwolf_noisy_25.89'
  data_reference: '/scratch/park/data/simulation_data/haystack/6000-lines-blurred-by-gaublur-std-4/GT'
  data_target: '/scratch/park/data/simulation_data/haystack/6000-lines-blurred-by-gaublur-std-4/blurred'
  image_dimension: 3
  direction: AtoB # direction of image translation: AtoB or BtoA
  serial_batches: False #if true, sample images in sequential order to make batches, otherwise sample them randomly

model_parameters:
  model: test # Source volume and Target volume 
  model_suffix: _A # which generator?
  input_nc: 1 # number of input image channels: 3 for RGB and 1 for grayscale
  output_nc: 1 # number of output image channels: 3 for RGB and 1 for grayscale
  ngf: 64 # number of gen filters in the last conv layer 
  netG: unet_deconv # specify generator architecture [resnet_9blocks | resnet_6blocks | unet_256 | unet_128]
  norm: instance_with_trackstats # instance normalization or batch normalization [instance | batch | spectral | none]
  init_type: kaiming # network initialization [normal | xavier | kaiming | orthogonal]
  init_gain: 0.02 # scaling factor for normal, xavier and orthogonal.
  no_dropout: False # no dropout for the generator. For cycleGAN, no_dropout is a default option.
 
training_parameters:
  isTrain: False 
  gpu_ids: [0] # gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU
  batch_size: 1
  # epoch_length: 1000 # how many iterations per epoch
  data_augmentation: 
    preprocess: addColorChannel # preprocessing for input images: [randomcrop | randomrotate | randomflip | normalize | none]
  learning_rate:
    lr: 0.0001
    beta1: 0.1
    momentum: 0.9
    lr_policy: constant # do not apply scheduler yet. 

monitoring_parameters: 
    save_epoch_freq: 1
    display_freq: 1000
    visual_projection_depth: 20
    
